### ISSUE TITLE
Please provide AppImage for download

### ISSUE THREAD

**Issue by probonopd** [jestrux/ladha#1]
https://github.com/jestrux/ladha/blob/66547c935ce07e5a5d1ec1b4cd4434a220ada672/electron-builder.json#L37

Please provide the AppImage for download on [GitHub Releases](https://github.com/jestrux/ladha/releases), thank you.

**Comment by jestrux** [comment]
@probonopd I've never had to build for linux so I'm not even sure what AppImage is.....could you please explain?

**Comment by jestrux** [comment]
Hey, I've added AppImage it to the releases as per your request. Notice that it's still in development, so I'd appreciate feedback on any bugs, features or unexpected behaviour.

**Comment by jestrux** [comment]
Hey @probonopd I've added AppImage it to the releases as per your request. Notice that it's still in development, so I'd appreciate feedback on any bugs, features or unexpected behaviour.
